# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InviteTeam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InviteTeam
  pod 'JTAppleCalendar', '~> 6.0'

  target 'InviteTeamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InviteTeamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
